(cl:in-package dsr_msgs-srv)
(cl:export '(EXTERNAL_FORCE_TORQUE-VAL
          EXTERNAL_FORCE_TORQUE
          EXTERNAL_DIGITAL_INPUT-VAL
          EXTERNAL_DIGITAL_INPUT
          EXTERNAL_DIGITAL_OUTPUT-VAL
          EXTERNAL_DIGITAL_OUTPUT
          EXTERNAL_ANALOG_INPUT-VAL
          EXTERNAL_ANALOG_INPUT
          EXTERNAL_ANALOG_OUTPUT-VAL
          EXTERNAL_ANALOG_OUTPUT
          SUCCESS-VAL
          SUCCESS
))