// Generated by gencpp from file dsr_msgs/ConfigCreateModbus.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_CONFIGCREATEMODBUS_H
#define DSR_MSGS_MESSAGE_CONFIGCREATEMODBUS_H

#include <ros/service_traits.h>


#include <dsr_msgs/ConfigCreateModbusRequest.h>
#include <dsr_msgs/ConfigCreateModbusResponse.h>


namespace dsr_msgs
{

struct ConfigCreateModbus
{

typedef ConfigCreateModbusRequest Request;
typedef ConfigCreateModbusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConfigCreateModbus
} // namespace dsr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dsr_msgs::ConfigCreateModbus > {
  static const char* value()
  {
    return "21b56fd5fb77f7fccfc8eb6d995cd64a";
  }

  static const char* value(const ::dsr_msgs::ConfigCreateModbus&) { return value(); }
};

template<>
struct DataType< ::dsr_msgs::ConfigCreateModbus > {
  static const char* value()
  {
    return "dsr_msgs/ConfigCreateModbus";
  }

  static const char* value(const ::dsr_msgs::ConfigCreateModbus&) { return value(); }
};


// service_traits::MD5Sum< ::dsr_msgs::ConfigCreateModbusRequest> should match
// service_traits::MD5Sum< ::dsr_msgs::ConfigCreateModbus >
template<>
struct MD5Sum< ::dsr_msgs::ConfigCreateModbusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::ConfigCreateModbus >::value();
  }
  static const char* value(const ::dsr_msgs::ConfigCreateModbusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::ConfigCreateModbusRequest> should match
// service_traits::DataType< ::dsr_msgs::ConfigCreateModbus >
template<>
struct DataType< ::dsr_msgs::ConfigCreateModbusRequest>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::ConfigCreateModbus >::value();
  }
  static const char* value(const ::dsr_msgs::ConfigCreateModbusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dsr_msgs::ConfigCreateModbusResponse> should match
// service_traits::MD5Sum< ::dsr_msgs::ConfigCreateModbus >
template<>
struct MD5Sum< ::dsr_msgs::ConfigCreateModbusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::ConfigCreateModbus >::value();
  }
  static const char* value(const ::dsr_msgs::ConfigCreateModbusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::ConfigCreateModbusResponse> should match
// service_traits::DataType< ::dsr_msgs::ConfigCreateModbus >
template<>
struct DataType< ::dsr_msgs::ConfigCreateModbusResponse>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::ConfigCreateModbus >::value();
  }
  static const char* value(const ::dsr_msgs::ConfigCreateModbusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DSR_MSGS_MESSAGE_CONFIGCREATEMODBUS_H
