// Generated by gencpp from file dsr_msgs/DisconnectRTControl.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_DISCONNECTRTCONTROL_H
#define DSR_MSGS_MESSAGE_DISCONNECTRTCONTROL_H

#include <ros/service_traits.h>


#include <dsr_msgs/DisconnectRTControlRequest.h>
#include <dsr_msgs/DisconnectRTControlResponse.h>


namespace dsr_msgs
{

struct DisconnectRTControl
{

typedef DisconnectRTControlRequest Request;
typedef DisconnectRTControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DisconnectRTControl
} // namespace dsr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dsr_msgs::DisconnectRTControl > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::dsr_msgs::DisconnectRTControl&) { return value(); }
};

template<>
struct DataType< ::dsr_msgs::DisconnectRTControl > {
  static const char* value()
  {
    return "dsr_msgs/DisconnectRTControl";
  }

  static const char* value(const ::dsr_msgs::DisconnectRTControl&) { return value(); }
};


// service_traits::MD5Sum< ::dsr_msgs::DisconnectRTControlRequest> should match
// service_traits::MD5Sum< ::dsr_msgs::DisconnectRTControl >
template<>
struct MD5Sum< ::dsr_msgs::DisconnectRTControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::DisconnectRTControl >::value();
  }
  static const char* value(const ::dsr_msgs::DisconnectRTControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::DisconnectRTControlRequest> should match
// service_traits::DataType< ::dsr_msgs::DisconnectRTControl >
template<>
struct DataType< ::dsr_msgs::DisconnectRTControlRequest>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::DisconnectRTControl >::value();
  }
  static const char* value(const ::dsr_msgs::DisconnectRTControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dsr_msgs::DisconnectRTControlResponse> should match
// service_traits::MD5Sum< ::dsr_msgs::DisconnectRTControl >
template<>
struct MD5Sum< ::dsr_msgs::DisconnectRTControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::DisconnectRTControl >::value();
  }
  static const char* value(const ::dsr_msgs::DisconnectRTControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::DisconnectRTControlResponse> should match
// service_traits::DataType< ::dsr_msgs::DisconnectRTControl >
template<>
struct DataType< ::dsr_msgs::DisconnectRTControlResponse>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::DisconnectRTControl >::value();
  }
  static const char* value(const ::dsr_msgs::DisconnectRTControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DSR_MSGS_MESSAGE_DISCONNECTRTCONTROL_H
