// Generated by gencpp from file dsr_msgs/DrlPause.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_DRLPAUSE_H
#define DSR_MSGS_MESSAGE_DRLPAUSE_H

#include <ros/service_traits.h>


#include <dsr_msgs/DrlPauseRequest.h>
#include <dsr_msgs/DrlPauseResponse.h>


namespace dsr_msgs
{

struct DrlPause
{

typedef DrlPauseRequest Request;
typedef DrlPauseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DrlPause
} // namespace dsr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dsr_msgs::DrlPause > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::dsr_msgs::DrlPause&) { return value(); }
};

template<>
struct DataType< ::dsr_msgs::DrlPause > {
  static const char* value()
  {
    return "dsr_msgs/DrlPause";
  }

  static const char* value(const ::dsr_msgs::DrlPause&) { return value(); }
};


// service_traits::MD5Sum< ::dsr_msgs::DrlPauseRequest> should match
// service_traits::MD5Sum< ::dsr_msgs::DrlPause >
template<>
struct MD5Sum< ::dsr_msgs::DrlPauseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::DrlPause >::value();
  }
  static const char* value(const ::dsr_msgs::DrlPauseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::DrlPauseRequest> should match
// service_traits::DataType< ::dsr_msgs::DrlPause >
template<>
struct DataType< ::dsr_msgs::DrlPauseRequest>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::DrlPause >::value();
  }
  static const char* value(const ::dsr_msgs::DrlPauseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dsr_msgs::DrlPauseResponse> should match
// service_traits::MD5Sum< ::dsr_msgs::DrlPause >
template<>
struct MD5Sum< ::dsr_msgs::DrlPauseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::DrlPause >::value();
  }
  static const char* value(const ::dsr_msgs::DrlPauseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::DrlPauseResponse> should match
// service_traits::DataType< ::dsr_msgs::DrlPause >
template<>
struct DataType< ::dsr_msgs::DrlPauseResponse>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::DrlPause >::value();
  }
  static const char* value(const ::dsr_msgs::DrlPauseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DSR_MSGS_MESSAGE_DRLPAUSE_H
