// Generated by gencpp from file dsr_msgs/GetCtrlBoxDigitalInputRequest.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_GETCTRLBOXDIGITALINPUTREQUEST_H
#define DSR_MSGS_MESSAGE_GETCTRLBOXDIGITALINPUTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dsr_msgs
{
template <class ContainerAllocator>
struct GetCtrlBoxDigitalInputRequest_
{
  typedef GetCtrlBoxDigitalInputRequest_<ContainerAllocator> Type;

  GetCtrlBoxDigitalInputRequest_()
    : index(0)  {
    }
  GetCtrlBoxDigitalInputRequest_(const ContainerAllocator& _alloc)
    : index(0)  {
  (void)_alloc;
    }



   typedef int8_t _index_type;
  _index_type index;





  typedef boost::shared_ptr< ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetCtrlBoxDigitalInputRequest_

typedef ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<std::allocator<void> > GetCtrlBoxDigitalInputRequest;

typedef boost::shared_ptr< ::dsr_msgs::GetCtrlBoxDigitalInputRequest > GetCtrlBoxDigitalInputRequestPtr;
typedef boost::shared_ptr< ::dsr_msgs::GetCtrlBoxDigitalInputRequest const> GetCtrlBoxDigitalInputRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator1> & lhs, const ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator1> & lhs, const ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dsr_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4ecff52046eaecf0190e650b1958286";
  }

  static const char* value(const ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4ecff52046eaecfULL;
  static const uint64_t static_value2 = 0x0190e650b1958286ULL;
};

template<class ContainerAllocator>
struct DataType< ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dsr_msgs/GetCtrlBoxDigitalInputRequest";
  }

  static const char* value(const ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#____________________________________________________________________________________________\n"
"# get_digital_input\n"
"# This service reads the I/O signals from digital contact points of the controller and reads the digital input contact value.\n"
"#____________________________________________________________________________________________\n"
"\n"
"int8        index    # Digital Input in Control Box(1 ~ 16) \n"
"                     # <GPIO_CTRLBOX_DIGITAL_INDEX>\n"
;
  }

  static const char* value(const ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCtrlBoxDigitalInputRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dsr_msgs::GetCtrlBoxDigitalInputRequest_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<int8_t>::stream(s, indent + "  ", v.index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DSR_MSGS_MESSAGE_GETCTRLBOXDIGITALINPUTREQUEST_H
