// Generated by gencpp from file dsr_msgs/GetCurrentTool.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_GETCURRENTTOOL_H
#define DSR_MSGS_MESSAGE_GETCURRENTTOOL_H

#include <ros/service_traits.h>


#include <dsr_msgs/GetCurrentToolRequest.h>
#include <dsr_msgs/GetCurrentToolResponse.h>


namespace dsr_msgs
{

struct GetCurrentTool
{

typedef GetCurrentToolRequest Request;
typedef GetCurrentToolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCurrentTool
} // namespace dsr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dsr_msgs::GetCurrentTool > {
  static const char* value()
  {
    return "4ed9e7e2e2815d295b7f655584191cad";
  }

  static const char* value(const ::dsr_msgs::GetCurrentTool&) { return value(); }
};

template<>
struct DataType< ::dsr_msgs::GetCurrentTool > {
  static const char* value()
  {
    return "dsr_msgs/GetCurrentTool";
  }

  static const char* value(const ::dsr_msgs::GetCurrentTool&) { return value(); }
};


// service_traits::MD5Sum< ::dsr_msgs::GetCurrentToolRequest> should match
// service_traits::MD5Sum< ::dsr_msgs::GetCurrentTool >
template<>
struct MD5Sum< ::dsr_msgs::GetCurrentToolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::GetCurrentTool >::value();
  }
  static const char* value(const ::dsr_msgs::GetCurrentToolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::GetCurrentToolRequest> should match
// service_traits::DataType< ::dsr_msgs::GetCurrentTool >
template<>
struct DataType< ::dsr_msgs::GetCurrentToolRequest>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::GetCurrentTool >::value();
  }
  static const char* value(const ::dsr_msgs::GetCurrentToolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dsr_msgs::GetCurrentToolResponse> should match
// service_traits::MD5Sum< ::dsr_msgs::GetCurrentTool >
template<>
struct MD5Sum< ::dsr_msgs::GetCurrentToolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::GetCurrentTool >::value();
  }
  static const char* value(const ::dsr_msgs::GetCurrentToolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::GetCurrentToolResponse> should match
// service_traits::DataType< ::dsr_msgs::GetCurrentTool >
template<>
struct DataType< ::dsr_msgs::GetCurrentToolResponse>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::GetCurrentTool >::value();
  }
  static const char* value(const ::dsr_msgs::GetCurrentToolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DSR_MSGS_MESSAGE_GETCURRENTTOOL_H
