// Generated by gencpp from file dsr_msgs/GetDesiredPosj.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_GETDESIREDPOSJ_H
#define DSR_MSGS_MESSAGE_GETDESIREDPOSJ_H

#include <ros/service_traits.h>


#include <dsr_msgs/GetDesiredPosjRequest.h>
#include <dsr_msgs/GetDesiredPosjResponse.h>


namespace dsr_msgs
{

struct GetDesiredPosj
{

typedef GetDesiredPosjRequest Request;
typedef GetDesiredPosjResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDesiredPosj
} // namespace dsr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dsr_msgs::GetDesiredPosj > {
  static const char* value()
  {
    return "3d228bb409a5fe0306e199313e3ed277";
  }

  static const char* value(const ::dsr_msgs::GetDesiredPosj&) { return value(); }
};

template<>
struct DataType< ::dsr_msgs::GetDesiredPosj > {
  static const char* value()
  {
    return "dsr_msgs/GetDesiredPosj";
  }

  static const char* value(const ::dsr_msgs::GetDesiredPosj&) { return value(); }
};


// service_traits::MD5Sum< ::dsr_msgs::GetDesiredPosjRequest> should match
// service_traits::MD5Sum< ::dsr_msgs::GetDesiredPosj >
template<>
struct MD5Sum< ::dsr_msgs::GetDesiredPosjRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::GetDesiredPosj >::value();
  }
  static const char* value(const ::dsr_msgs::GetDesiredPosjRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::GetDesiredPosjRequest> should match
// service_traits::DataType< ::dsr_msgs::GetDesiredPosj >
template<>
struct DataType< ::dsr_msgs::GetDesiredPosjRequest>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::GetDesiredPosj >::value();
  }
  static const char* value(const ::dsr_msgs::GetDesiredPosjRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dsr_msgs::GetDesiredPosjResponse> should match
// service_traits::MD5Sum< ::dsr_msgs::GetDesiredPosj >
template<>
struct MD5Sum< ::dsr_msgs::GetDesiredPosjResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::GetDesiredPosj >::value();
  }
  static const char* value(const ::dsr_msgs::GetDesiredPosjResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::GetDesiredPosjResponse> should match
// service_traits::DataType< ::dsr_msgs::GetDesiredPosj >
template<>
struct DataType< ::dsr_msgs::GetDesiredPosjResponse>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::GetDesiredPosj >::value();
  }
  static const char* value(const ::dsr_msgs::GetDesiredPosjResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DSR_MSGS_MESSAGE_GETDESIREDPOSJ_H
