// Generated by gencpp from file dsr_msgs/GetRTControlInputDataListResponse.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_GETRTCONTROLINPUTDATALISTRESPONSE_H
#define DSR_MSGS_MESSAGE_GETRTCONTROLINPUTDATALISTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dsr_msgs
{
template <class ContainerAllocator>
struct GetRTControlInputDataListResponse_
{
  typedef GetRTControlInputDataListResponse_<ContainerAllocator> Type;

  GetRTControlInputDataListResponse_()
    : success(false)
    , data()  {
    }
  GetRTControlInputDataListResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetRTControlInputDataListResponse_

typedef ::dsr_msgs::GetRTControlInputDataListResponse_<std::allocator<void> > GetRTControlInputDataListResponse;

typedef boost::shared_ptr< ::dsr_msgs::GetRTControlInputDataListResponse > GetRTControlInputDataListResponsePtr;
typedef boost::shared_ptr< ::dsr_msgs::GetRTControlInputDataListResponse const> GetRTControlInputDataListResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator1> & lhs, const ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator1> & lhs, const ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dsr_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18fa309f5109d7d404151da58f11cb68";
  }

  static const char* value(const ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18fa309f5109d7d4ULL;
  static const uint64_t static_value2 = 0x04151da58f11cb68ULL;
};

template<class ContainerAllocator>
struct DataType< ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dsr_msgs/GetRTControlInputDataListResponse";
  }

  static const char* value(const ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool       success\n"
"string     data\n"
;
  }

  static const char* value(const ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRTControlInputDataListResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dsr_msgs::GetRTControlInputDataListResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DSR_MSGS_MESSAGE_GETRTCONTROLINPUTDATALISTRESPONSE_H
