// Generated by gencpp from file dsr_msgs/GetToolDigitalOutputResponse.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_GETTOOLDIGITALOUTPUTRESPONSE_H
#define DSR_MSGS_MESSAGE_GETTOOLDIGITALOUTPUTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dsr_msgs
{
template <class ContainerAllocator>
struct GetToolDigitalOutputResponse_
{
  typedef GetToolDigitalOutputResponse_<ContainerAllocator> Type;

  GetToolDigitalOutputResponse_()
    : value(0)
    , success(false)  {
    }
  GetToolDigitalOutputResponse_(const ContainerAllocator& _alloc)
    : value(0)
    , success(false)  {
  (void)_alloc;
    }



   typedef int8_t _value_type;
  _value_type value;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetToolDigitalOutputResponse_

typedef ::dsr_msgs::GetToolDigitalOutputResponse_<std::allocator<void> > GetToolDigitalOutputResponse;

typedef boost::shared_ptr< ::dsr_msgs::GetToolDigitalOutputResponse > GetToolDigitalOutputResponsePtr;
typedef boost::shared_ptr< ::dsr_msgs::GetToolDigitalOutputResponse const> GetToolDigitalOutputResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator1> & lhs, const ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator1> & lhs, const ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dsr_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2002a87d9e124a06af2057212386843f";
  }

  static const char* value(const ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2002a87d9e124a06ULL;
  static const uint64_t static_value2 = 0xaf2057212386843fULL;
};

template<class ContainerAllocator>
struct DataType< ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dsr_msgs/GetToolDigitalOutputResponse";
  }

  static const char* value(const ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8       value   # Current output status (0 : ON, 1 : OFF)\n"
"bool       success\n"
;
  }

  static const char* value(const ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetToolDigitalOutputResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dsr_msgs::GetToolDigitalOutputResponse_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<int8_t>::stream(s, indent + "  ", v.value);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DSR_MSGS_MESSAGE_GETTOOLDIGITALOUTPUTRESPONSE_H
