// Generated by gencpp from file dsr_msgs/IkinExResponse.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_IKINEXRESPONSE_H
#define DSR_MSGS_MESSAGE_IKINEXRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dsr_msgs
{
template <class ContainerAllocator>
struct IkinExResponse_
{
  typedef IkinExResponse_<ContainerAllocator> Type;

  IkinExResponse_()
    : conv_posj()
    , status(false)
    , success(false)  {
      conv_posj.assign(0.0);
  }
  IkinExResponse_(const ContainerAllocator& _alloc)
    : conv_posj()
    , status(false)
    , success(false)  {
  (void)_alloc;
      conv_posj.assign(0.0);
  }



   typedef boost::array<double, 6>  _conv_posj_type;
  _conv_posj_type conv_posj;

   typedef uint8_t _status_type;
  _status_type status;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::dsr_msgs::IkinExResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dsr_msgs::IkinExResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IkinExResponse_

typedef ::dsr_msgs::IkinExResponse_<std::allocator<void> > IkinExResponse;

typedef boost::shared_ptr< ::dsr_msgs::IkinExResponse > IkinExResponsePtr;
typedef boost::shared_ptr< ::dsr_msgs::IkinExResponse const> IkinExResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dsr_msgs::IkinExResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dsr_msgs::IkinExResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dsr_msgs::IkinExResponse_<ContainerAllocator1> & lhs, const ::dsr_msgs::IkinExResponse_<ContainerAllocator2> & rhs)
{
  return lhs.conv_posj == rhs.conv_posj &&
    lhs.status == rhs.status &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dsr_msgs::IkinExResponse_<ContainerAllocator1> & lhs, const ::dsr_msgs::IkinExResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dsr_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dsr_msgs::IkinExResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dsr_msgs::IkinExResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dsr_msgs::IkinExResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dsr_msgs::IkinExResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dsr_msgs::IkinExResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dsr_msgs::IkinExResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dsr_msgs::IkinExResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a262c9bd7c19457d248b6a5e85981bc";
  }

  static const char* value(const ::dsr_msgs::IkinExResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a262c9bd7c19457ULL;
  static const uint64_t static_value2 = 0xd248b6a5e85981bcULL;
};

template<class ContainerAllocator>
struct DataType< ::dsr_msgs::IkinExResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dsr_msgs/IkinExResponse";
  }

  static const char* value(const ::dsr_msgs::IkinExResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dsr_msgs::IkinExResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[6] conv_posj         # joint pos(posj)  \n"
"bool       status\n"
"bool       success\n"
"\n"
;
  }

  static const char* value(const ::dsr_msgs::IkinExResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dsr_msgs::IkinExResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.conv_posj);
      stream.next(m.status);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IkinExResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dsr_msgs::IkinExResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dsr_msgs::IkinExResponse_<ContainerAllocator>& v)
  {
    s << indent << "conv_posj[]" << std::endl;
    for (size_t i = 0; i < v.conv_posj.size(); ++i)
    {
      s << indent << "  conv_posj[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.conv_posj[i]);
    }
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DSR_MSGS_MESSAGE_IKINEXRESPONSE_H
