// Generated by gencpp from file dsr_msgs/MoveJointx.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_MOVEJOINTX_H
#define DSR_MSGS_MESSAGE_MOVEJOINTX_H

#include <ros/service_traits.h>


#include <dsr_msgs/MoveJointxRequest.h>
#include <dsr_msgs/MoveJointxResponse.h>


namespace dsr_msgs
{

struct MoveJointx
{

typedef MoveJointxRequest Request;
typedef MoveJointxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveJointx
} // namespace dsr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dsr_msgs::MoveJointx > {
  static const char* value()
  {
    return "b9419696b37ce5162db29de34d49184f";
  }

  static const char* value(const ::dsr_msgs::MoveJointx&) { return value(); }
};

template<>
struct DataType< ::dsr_msgs::MoveJointx > {
  static const char* value()
  {
    return "dsr_msgs/MoveJointx";
  }

  static const char* value(const ::dsr_msgs::MoveJointx&) { return value(); }
};


// service_traits::MD5Sum< ::dsr_msgs::MoveJointxRequest> should match
// service_traits::MD5Sum< ::dsr_msgs::MoveJointx >
template<>
struct MD5Sum< ::dsr_msgs::MoveJointxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::MoveJointx >::value();
  }
  static const char* value(const ::dsr_msgs::MoveJointxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::MoveJointxRequest> should match
// service_traits::DataType< ::dsr_msgs::MoveJointx >
template<>
struct DataType< ::dsr_msgs::MoveJointxRequest>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::MoveJointx >::value();
  }
  static const char* value(const ::dsr_msgs::MoveJointxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dsr_msgs::MoveJointxResponse> should match
// service_traits::MD5Sum< ::dsr_msgs::MoveJointx >
template<>
struct MD5Sum< ::dsr_msgs::MoveJointxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::MoveJointx >::value();
  }
  static const char* value(const ::dsr_msgs::MoveJointxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::MoveJointxResponse> should match
// service_traits::DataType< ::dsr_msgs::MoveJointx >
template<>
struct DataType< ::dsr_msgs::MoveJointxResponse>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::MoveJointx >::value();
  }
  static const char* value(const ::dsr_msgs::MoveJointxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DSR_MSGS_MESSAGE_MOVEJOINTX_H
