// Generated by gencpp from file dsr_msgs/MoveLine.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_MOVELINE_H
#define DSR_MSGS_MESSAGE_MOVELINE_H

#include <ros/service_traits.h>


#include <dsr_msgs/MoveLineRequest.h>
#include <dsr_msgs/MoveLineResponse.h>


namespace dsr_msgs
{

struct MoveLine
{

typedef MoveLineRequest Request;
typedef MoveLineResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveLine
} // namespace dsr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dsr_msgs::MoveLine > {
  static const char* value()
  {
    return "444a9dab874993faadb186c2ade7c1bc";
  }

  static const char* value(const ::dsr_msgs::MoveLine&) { return value(); }
};

template<>
struct DataType< ::dsr_msgs::MoveLine > {
  static const char* value()
  {
    return "dsr_msgs/MoveLine";
  }

  static const char* value(const ::dsr_msgs::MoveLine&) { return value(); }
};


// service_traits::MD5Sum< ::dsr_msgs::MoveLineRequest> should match
// service_traits::MD5Sum< ::dsr_msgs::MoveLine >
template<>
struct MD5Sum< ::dsr_msgs::MoveLineRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::MoveLine >::value();
  }
  static const char* value(const ::dsr_msgs::MoveLineRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::MoveLineRequest> should match
// service_traits::DataType< ::dsr_msgs::MoveLine >
template<>
struct DataType< ::dsr_msgs::MoveLineRequest>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::MoveLine >::value();
  }
  static const char* value(const ::dsr_msgs::MoveLineRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dsr_msgs::MoveLineResponse> should match
// service_traits::MD5Sum< ::dsr_msgs::MoveLine >
template<>
struct MD5Sum< ::dsr_msgs::MoveLineResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::MoveLine >::value();
  }
  static const char* value(const ::dsr_msgs::MoveLineResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::MoveLineResponse> should match
// service_traits::DataType< ::dsr_msgs::MoveLine >
template<>
struct DataType< ::dsr_msgs::MoveLineResponse>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::MoveLine >::value();
  }
  static const char* value(const ::dsr_msgs::MoveLineResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DSR_MSGS_MESSAGE_MOVELINE_H
