// Generated by gencpp from file dsr_msgs/MovePause.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_MOVEPAUSE_H
#define DSR_MSGS_MESSAGE_MOVEPAUSE_H

#include <ros/service_traits.h>


#include <dsr_msgs/MovePauseRequest.h>
#include <dsr_msgs/MovePauseResponse.h>


namespace dsr_msgs
{

struct MovePause
{

typedef MovePauseRequest Request;
typedef MovePauseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MovePause
} // namespace dsr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dsr_msgs::MovePause > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::dsr_msgs::MovePause&) { return value(); }
};

template<>
struct DataType< ::dsr_msgs::MovePause > {
  static const char* value()
  {
    return "dsr_msgs/MovePause";
  }

  static const char* value(const ::dsr_msgs::MovePause&) { return value(); }
};


// service_traits::MD5Sum< ::dsr_msgs::MovePauseRequest> should match
// service_traits::MD5Sum< ::dsr_msgs::MovePause >
template<>
struct MD5Sum< ::dsr_msgs::MovePauseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::MovePause >::value();
  }
  static const char* value(const ::dsr_msgs::MovePauseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::MovePauseRequest> should match
// service_traits::DataType< ::dsr_msgs::MovePause >
template<>
struct DataType< ::dsr_msgs::MovePauseRequest>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::MovePause >::value();
  }
  static const char* value(const ::dsr_msgs::MovePauseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dsr_msgs::MovePauseResponse> should match
// service_traits::MD5Sum< ::dsr_msgs::MovePause >
template<>
struct MD5Sum< ::dsr_msgs::MovePauseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::MovePause >::value();
  }
  static const char* value(const ::dsr_msgs::MovePauseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::MovePauseResponse> should match
// service_traits::DataType< ::dsr_msgs::MovePause >
template<>
struct DataType< ::dsr_msgs::MovePauseResponse>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::MovePause >::value();
  }
  static const char* value(const ::dsr_msgs::MovePauseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DSR_MSGS_MESSAGE_MOVEPAUSE_H
