// Generated by gencpp from file dsr_msgs/MoveHome.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_MOVEHOME_H
#define DSR_MSGS_MESSAGE_MOVEHOME_H

#include <ros/service_traits.h>


#include <dsr_msgs/MoveHomeRequest.h>
#include <dsr_msgs/MoveHomeResponse.h>


namespace dsr_msgs
{

struct MoveHome
{

typedef MoveHomeRequest Request;
typedef MoveHomeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveHome
} // namespace dsr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dsr_msgs::MoveHome > {
  static const char* value()
  {
    return "1df045e08f5aa30b46232621f50af2fd";
  }

  static const char* value(const ::dsr_msgs::MoveHome&) { return value(); }
};

template<>
struct DataType< ::dsr_msgs::MoveHome > {
  static const char* value()
  {
    return "dsr_msgs/MoveHome";
  }

  static const char* value(const ::dsr_msgs::MoveHome&) { return value(); }
};


// service_traits::MD5Sum< ::dsr_msgs::MoveHomeRequest> should match
// service_traits::MD5Sum< ::dsr_msgs::MoveHome >
template<>
struct MD5Sum< ::dsr_msgs::MoveHomeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::MoveHome >::value();
  }
  static const char* value(const ::dsr_msgs::MoveHomeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::MoveHomeRequest> should match
// service_traits::DataType< ::dsr_msgs::MoveHome >
template<>
struct DataType< ::dsr_msgs::MoveHomeRequest>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::MoveHome >::value();
  }
  static const char* value(const ::dsr_msgs::MoveHomeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dsr_msgs::MoveHomeResponse> should match
// service_traits::MD5Sum< ::dsr_msgs::MoveHome >
template<>
struct MD5Sum< ::dsr_msgs::MoveHomeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::MoveHome >::value();
  }
  static const char* value(const ::dsr_msgs::MoveHomeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::MoveHomeResponse> should match
// service_traits::DataType< ::dsr_msgs::MoveHome >
template<>
struct DataType< ::dsr_msgs::MoveHomeResponse>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::MoveHome >::value();
  }
  static const char* value(const ::dsr_msgs::MoveHomeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DSR_MSGS_MESSAGE_MOVEHOME_H
