// Generated by gencpp from file dsr_msgs/ParallelAxis1.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_PARALLELAXIS1_H
#define DSR_MSGS_MESSAGE_PARALLELAXIS1_H

#include <ros/service_traits.h>


#include <dsr_msgs/ParallelAxis1Request.h>
#include <dsr_msgs/ParallelAxis1Response.h>


namespace dsr_msgs
{

struct ParallelAxis1
{

typedef ParallelAxis1Request Request;
typedef ParallelAxis1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParallelAxis1
} // namespace dsr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dsr_msgs::ParallelAxis1 > {
  static const char* value()
  {
    return "f95b1583e6e04ac8d77cbe47de2af332";
  }

  static const char* value(const ::dsr_msgs::ParallelAxis1&) { return value(); }
};

template<>
struct DataType< ::dsr_msgs::ParallelAxis1 > {
  static const char* value()
  {
    return "dsr_msgs/ParallelAxis1";
  }

  static const char* value(const ::dsr_msgs::ParallelAxis1&) { return value(); }
};


// service_traits::MD5Sum< ::dsr_msgs::ParallelAxis1Request> should match
// service_traits::MD5Sum< ::dsr_msgs::ParallelAxis1 >
template<>
struct MD5Sum< ::dsr_msgs::ParallelAxis1Request>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::ParallelAxis1 >::value();
  }
  static const char* value(const ::dsr_msgs::ParallelAxis1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::ParallelAxis1Request> should match
// service_traits::DataType< ::dsr_msgs::ParallelAxis1 >
template<>
struct DataType< ::dsr_msgs::ParallelAxis1Request>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::ParallelAxis1 >::value();
  }
  static const char* value(const ::dsr_msgs::ParallelAxis1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dsr_msgs::ParallelAxis1Response> should match
// service_traits::MD5Sum< ::dsr_msgs::ParallelAxis1 >
template<>
struct MD5Sum< ::dsr_msgs::ParallelAxis1Response>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::ParallelAxis1 >::value();
  }
  static const char* value(const ::dsr_msgs::ParallelAxis1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::ParallelAxis1Response> should match
// service_traits::DataType< ::dsr_msgs::ParallelAxis1 >
template<>
struct DataType< ::dsr_msgs::ParallelAxis1Response>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::ParallelAxis1 >::value();
  }
  static const char* value(const ::dsr_msgs::ParallelAxis1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DSR_MSGS_MESSAGE_PARALLELAXIS1_H
