// Generated by gencpp from file dsr_msgs/ReleaseProtectiveStop.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_RELEASEPROTECTIVESTOP_H
#define DSR_MSGS_MESSAGE_RELEASEPROTECTIVESTOP_H

#include <ros/service_traits.h>


#include <dsr_msgs/ReleaseProtectiveStopRequest.h>
#include <dsr_msgs/ReleaseProtectiveStopResponse.h>


namespace dsr_msgs
{

struct ReleaseProtectiveStop
{

typedef ReleaseProtectiveStopRequest Request;
typedef ReleaseProtectiveStopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReleaseProtectiveStop
} // namespace dsr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dsr_msgs::ReleaseProtectiveStop > {
  static const char* value()
  {
    return "3cf8efd6d59d99783a077dda000b1bbb";
  }

  static const char* value(const ::dsr_msgs::ReleaseProtectiveStop&) { return value(); }
};

template<>
struct DataType< ::dsr_msgs::ReleaseProtectiveStop > {
  static const char* value()
  {
    return "dsr_msgs/ReleaseProtectiveStop";
  }

  static const char* value(const ::dsr_msgs::ReleaseProtectiveStop&) { return value(); }
};


// service_traits::MD5Sum< ::dsr_msgs::ReleaseProtectiveStopRequest> should match
// service_traits::MD5Sum< ::dsr_msgs::ReleaseProtectiveStop >
template<>
struct MD5Sum< ::dsr_msgs::ReleaseProtectiveStopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::ReleaseProtectiveStop >::value();
  }
  static const char* value(const ::dsr_msgs::ReleaseProtectiveStopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::ReleaseProtectiveStopRequest> should match
// service_traits::DataType< ::dsr_msgs::ReleaseProtectiveStop >
template<>
struct DataType< ::dsr_msgs::ReleaseProtectiveStopRequest>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::ReleaseProtectiveStop >::value();
  }
  static const char* value(const ::dsr_msgs::ReleaseProtectiveStopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dsr_msgs::ReleaseProtectiveStopResponse> should match
// service_traits::MD5Sum< ::dsr_msgs::ReleaseProtectiveStop >
template<>
struct MD5Sum< ::dsr_msgs::ReleaseProtectiveStopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::ReleaseProtectiveStop >::value();
  }
  static const char* value(const ::dsr_msgs::ReleaseProtectiveStopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::ReleaseProtectiveStopResponse> should match
// service_traits::DataType< ::dsr_msgs::ReleaseProtectiveStop >
template<>
struct DataType< ::dsr_msgs::ReleaseProtectiveStopResponse>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::ReleaseProtectiveStop >::value();
  }
  static const char* value(const ::dsr_msgs::ReleaseProtectiveStopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DSR_MSGS_MESSAGE_RELEASEPROTECTIVESTOP_H
