// Generated by gencpp from file dsr_msgs/ReleaseProtectiveStopRequest.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_RELEASEPROTECTIVESTOPREQUEST_H
#define DSR_MSGS_MESSAGE_RELEASEPROTECTIVESTOPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dsr_msgs
{
template <class ContainerAllocator>
struct ReleaseProtectiveStopRequest_
{
  typedef ReleaseProtectiveStopRequest_<ContainerAllocator> Type;

  ReleaseProtectiveStopRequest_()
    : release_mode(0)  {
    }
  ReleaseProtectiveStopRequest_(const ContainerAllocator& _alloc)
    : release_mode(0)  {
  (void)_alloc;
    }



   typedef int8_t _release_mode_type;
  _release_mode_type release_mode;





  typedef boost::shared_ptr< ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReleaseProtectiveStopRequest_

typedef ::dsr_msgs::ReleaseProtectiveStopRequest_<std::allocator<void> > ReleaseProtectiveStopRequest;

typedef boost::shared_ptr< ::dsr_msgs::ReleaseProtectiveStopRequest > ReleaseProtectiveStopRequestPtr;
typedef boost::shared_ptr< ::dsr_msgs::ReleaseProtectiveStopRequest const> ReleaseProtectiveStopRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator1> & lhs, const ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator2> & rhs)
{
  return lhs.release_mode == rhs.release_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator1> & lhs, const ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dsr_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8a44b3d82288e0e3be18ede2666de6e";
  }

  static const char* value(const ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8a44b3d82288e0eULL;
  static const uint64_t static_value2 = 0x3be18ede2666de6eULL;
};

template<class ContainerAllocator>
struct DataType< ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dsr_msgs/ReleaseProtectiveStopRequest";
  }

  static const char* value(const ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#____________________________________________________________________________________________\n"
"# release_protective_stop\n"
"#____________________________________________________________________________________________\n"
"\n"
"int8 release_mode     # 0=RELEASE_MODE_STOP, 1=RELEASE_MODE_RESUME, 2=RELEASE_MODE_RELEASE, 3=RELEASE_MODE_RESET\n"
;
  }

  static const char* value(const ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.release_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReleaseProtectiveStopRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dsr_msgs::ReleaseProtectiveStopRequest_<ContainerAllocator>& v)
  {
    s << indent << "release_mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.release_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DSR_MSGS_MESSAGE_RELEASEPROTECTIVESTOPREQUEST_H
