// Generated by gencpp from file dsr_msgs/ResetWorkpieceWeight.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_RESETWORKPIECEWEIGHT_H
#define DSR_MSGS_MESSAGE_RESETWORKPIECEWEIGHT_H

#include <ros/service_traits.h>


#include <dsr_msgs/ResetWorkpieceWeightRequest.h>
#include <dsr_msgs/ResetWorkpieceWeightResponse.h>


namespace dsr_msgs
{

struct ResetWorkpieceWeight
{

typedef ResetWorkpieceWeightRequest Request;
typedef ResetWorkpieceWeightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetWorkpieceWeight
} // namespace dsr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dsr_msgs::ResetWorkpieceWeight > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::dsr_msgs::ResetWorkpieceWeight&) { return value(); }
};

template<>
struct DataType< ::dsr_msgs::ResetWorkpieceWeight > {
  static const char* value()
  {
    return "dsr_msgs/ResetWorkpieceWeight";
  }

  static const char* value(const ::dsr_msgs::ResetWorkpieceWeight&) { return value(); }
};


// service_traits::MD5Sum< ::dsr_msgs::ResetWorkpieceWeightRequest> should match
// service_traits::MD5Sum< ::dsr_msgs::ResetWorkpieceWeight >
template<>
struct MD5Sum< ::dsr_msgs::ResetWorkpieceWeightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::ResetWorkpieceWeight >::value();
  }
  static const char* value(const ::dsr_msgs::ResetWorkpieceWeightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::ResetWorkpieceWeightRequest> should match
// service_traits::DataType< ::dsr_msgs::ResetWorkpieceWeight >
template<>
struct DataType< ::dsr_msgs::ResetWorkpieceWeightRequest>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::ResetWorkpieceWeight >::value();
  }
  static const char* value(const ::dsr_msgs::ResetWorkpieceWeightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dsr_msgs::ResetWorkpieceWeightResponse> should match
// service_traits::MD5Sum< ::dsr_msgs::ResetWorkpieceWeight >
template<>
struct MD5Sum< ::dsr_msgs::ResetWorkpieceWeightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::ResetWorkpieceWeight >::value();
  }
  static const char* value(const ::dsr_msgs::ResetWorkpieceWeightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::ResetWorkpieceWeightResponse> should match
// service_traits::DataType< ::dsr_msgs::ResetWorkpieceWeight >
template<>
struct DataType< ::dsr_msgs::ResetWorkpieceWeightResponse>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::ResetWorkpieceWeight >::value();
  }
  static const char* value(const ::dsr_msgs::ResetWorkpieceWeightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DSR_MSGS_MESSAGE_RESETWORKPIECEWEIGHT_H
