// Generated by gencpp from file dsr_msgs/ServoLStream.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_SERVOLSTREAM_H
#define DSR_MSGS_MESSAGE_SERVOLSTREAM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dsr_msgs
{
template <class ContainerAllocator>
struct ServoLStream_
{
  typedef ServoLStream_<ContainerAllocator> Type;

  ServoLStream_()
    : pos()
    , vel()
    , acc()
    , time(0.0)  {
      pos.assign(0.0);

      vel.assign(0.0);

      acc.assign(0.0);
  }
  ServoLStream_(const ContainerAllocator& _alloc)
    : pos()
    , vel()
    , acc()
    , time(0.0)  {
  (void)_alloc;
      pos.assign(0.0);

      vel.assign(0.0);

      acc.assign(0.0);
  }



   typedef boost::array<double, 6>  _pos_type;
  _pos_type pos;

   typedef boost::array<double, 2>  _vel_type;
  _vel_type vel;

   typedef boost::array<double, 2>  _acc_type;
  _acc_type acc;

   typedef double _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::dsr_msgs::ServoLStream_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dsr_msgs::ServoLStream_<ContainerAllocator> const> ConstPtr;

}; // struct ServoLStream_

typedef ::dsr_msgs::ServoLStream_<std::allocator<void> > ServoLStream;

typedef boost::shared_ptr< ::dsr_msgs::ServoLStream > ServoLStreamPtr;
typedef boost::shared_ptr< ::dsr_msgs::ServoLStream const> ServoLStreamConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dsr_msgs::ServoLStream_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dsr_msgs::ServoLStream_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dsr_msgs::ServoLStream_<ContainerAllocator1> & lhs, const ::dsr_msgs::ServoLStream_<ContainerAllocator2> & rhs)
{
  return lhs.pos == rhs.pos &&
    lhs.vel == rhs.vel &&
    lhs.acc == rhs.acc &&
    lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dsr_msgs::ServoLStream_<ContainerAllocator1> & lhs, const ::dsr_msgs::ServoLStream_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dsr_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dsr_msgs::ServoLStream_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dsr_msgs::ServoLStream_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dsr_msgs::ServoLStream_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dsr_msgs::ServoLStream_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dsr_msgs::ServoLStream_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dsr_msgs::ServoLStream_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dsr_msgs::ServoLStream_<ContainerAllocator> >
{
  static const char* value()
  {
    return "faef3261e269f88f638555affcbeea57";
  }

  static const char* value(const ::dsr_msgs::ServoLStream_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfaef3261e269f88fULL;
  static const uint64_t static_value2 = 0x638555affcbeea57ULL;
};

template<class ContainerAllocator>
struct DataType< ::dsr_msgs::ServoLStream_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dsr_msgs/ServoLStream";
  }

  static const char* value(const ::dsr_msgs::ServoLStream_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dsr_msgs::ServoLStream_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#____________________________________________________________________________________________\n"
"# servol\n"
"# \n"
"#____________________________________________________________________________________________\n"
"\n"
"float64[6] pos               # position  \n"
"float64[2] vel               # velocity\n"
"float64[2] acc               # acceleration\n"
"float64    time              # time\n"
;
  }

  static const char* value(const ::dsr_msgs::ServoLStream_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dsr_msgs::ServoLStream_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos);
      stream.next(m.vel);
      stream.next(m.acc);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoLStream_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dsr_msgs::ServoLStream_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dsr_msgs::ServoLStream_<ContainerAllocator>& v)
  {
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pos[i]);
    }
    s << indent << "vel[]" << std::endl;
    for (size_t i = 0; i < v.vel.size(); ++i)
    {
      s << indent << "  vel[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.vel[i]);
    }
    s << indent << "acc[]" << std::endl;
    for (size_t i = 0; i < v.acc.size(); ++i)
    {
      s << indent << "  acc[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.acc[i]);
    }
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DSR_MSGS_MESSAGE_SERVOLSTREAM_H
