// Generated by gencpp from file dsr_msgs/SetAccXRT.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_SETACCXRT_H
#define DSR_MSGS_MESSAGE_SETACCXRT_H

#include <ros/service_traits.h>


#include <dsr_msgs/SetAccXRTRequest.h>
#include <dsr_msgs/SetAccXRTResponse.h>


namespace dsr_msgs
{

struct SetAccXRT
{

typedef SetAccXRTRequest Request;
typedef SetAccXRTResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAccXRT
} // namespace dsr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dsr_msgs::SetAccXRT > {
  static const char* value()
  {
    return "761d85a527beb96265a49a9c48c83232";
  }

  static const char* value(const ::dsr_msgs::SetAccXRT&) { return value(); }
};

template<>
struct DataType< ::dsr_msgs::SetAccXRT > {
  static const char* value()
  {
    return "dsr_msgs/SetAccXRT";
  }

  static const char* value(const ::dsr_msgs::SetAccXRT&) { return value(); }
};


// service_traits::MD5Sum< ::dsr_msgs::SetAccXRTRequest> should match
// service_traits::MD5Sum< ::dsr_msgs::SetAccXRT >
template<>
struct MD5Sum< ::dsr_msgs::SetAccXRTRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::SetAccXRT >::value();
  }
  static const char* value(const ::dsr_msgs::SetAccXRTRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::SetAccXRTRequest> should match
// service_traits::DataType< ::dsr_msgs::SetAccXRT >
template<>
struct DataType< ::dsr_msgs::SetAccXRTRequest>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::SetAccXRT >::value();
  }
  static const char* value(const ::dsr_msgs::SetAccXRTRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dsr_msgs::SetAccXRTResponse> should match
// service_traits::MD5Sum< ::dsr_msgs::SetAccXRT >
template<>
struct MD5Sum< ::dsr_msgs::SetAccXRTResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::SetAccXRT >::value();
  }
  static const char* value(const ::dsr_msgs::SetAccXRTResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::SetAccXRTResponse> should match
// service_traits::DataType< ::dsr_msgs::SetAccXRT >
template<>
struct DataType< ::dsr_msgs::SetAccXRTResponse>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::SetAccXRT >::value();
  }
  static const char* value(const ::dsr_msgs::SetAccXRTResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DSR_MSGS_MESSAGE_SETACCXRT_H
