// Generated by gencpp from file dsr_msgs/SetRobotSpeedModeRequest.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_SETROBOTSPEEDMODEREQUEST_H
#define DSR_MSGS_MESSAGE_SETROBOTSPEEDMODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dsr_msgs
{
template <class ContainerAllocator>
struct SetRobotSpeedModeRequest_
{
  typedef SetRobotSpeedModeRequest_<ContainerAllocator> Type;

  SetRobotSpeedModeRequest_()
    : speed_mode(0)  {
    }
  SetRobotSpeedModeRequest_(const ContainerAllocator& _alloc)
    : speed_mode(0)  {
  (void)_alloc;
    }



   typedef int8_t _speed_mode_type;
  _speed_mode_type speed_mode;





  typedef boost::shared_ptr< ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRobotSpeedModeRequest_

typedef ::dsr_msgs::SetRobotSpeedModeRequest_<std::allocator<void> > SetRobotSpeedModeRequest;

typedef boost::shared_ptr< ::dsr_msgs::SetRobotSpeedModeRequest > SetRobotSpeedModeRequestPtr;
typedef boost::shared_ptr< ::dsr_msgs::SetRobotSpeedModeRequest const> SetRobotSpeedModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator1> & lhs, const ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.speed_mode == rhs.speed_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator1> & lhs, const ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dsr_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19b88c6c53fbc4047e5743c63539f425";
  }

  static const char* value(const ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19b88c6c53fbc404ULL;
  static const uint64_t static_value2 = 0x7e5743c63539f425ULL;
};

template<class ContainerAllocator>
struct DataType< ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dsr_msgs/SetRobotSpeedModeRequest";
  }

  static const char* value(const ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#____________________________________________________________________________________________\n"
"# set_robot_speed_mode\n"
"#____________________________________________________________________________________________\n"
"\n"
"int8 speed_mode # 0 : SPEED_NORMAL_MODE, 1 : SPEED_REDUCED_MODE\n"
;
  }

  static const char* value(const ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRobotSpeedModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dsr_msgs::SetRobotSpeedModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "speed_mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.speed_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DSR_MSGS_MESSAGE_SETROBOTSPEEDMODEREQUEST_H
