// Generated by gencpp from file dsr_msgs/SetRefCoord.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_SETREFCOORD_H
#define DSR_MSGS_MESSAGE_SETREFCOORD_H

#include <ros/service_traits.h>


#include <dsr_msgs/SetRefCoordRequest.h>
#include <dsr_msgs/SetRefCoordResponse.h>


namespace dsr_msgs
{

struct SetRefCoord
{

typedef SetRefCoordRequest Request;
typedef SetRefCoordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRefCoord
} // namespace dsr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dsr_msgs::SetRefCoord > {
  static const char* value()
  {
    return "1e3275b6f46c8260502524b4e6bedf9c";
  }

  static const char* value(const ::dsr_msgs::SetRefCoord&) { return value(); }
};

template<>
struct DataType< ::dsr_msgs::SetRefCoord > {
  static const char* value()
  {
    return "dsr_msgs/SetRefCoord";
  }

  static const char* value(const ::dsr_msgs::SetRefCoord&) { return value(); }
};


// service_traits::MD5Sum< ::dsr_msgs::SetRefCoordRequest> should match
// service_traits::MD5Sum< ::dsr_msgs::SetRefCoord >
template<>
struct MD5Sum< ::dsr_msgs::SetRefCoordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::SetRefCoord >::value();
  }
  static const char* value(const ::dsr_msgs::SetRefCoordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::SetRefCoordRequest> should match
// service_traits::DataType< ::dsr_msgs::SetRefCoord >
template<>
struct DataType< ::dsr_msgs::SetRefCoordRequest>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::SetRefCoord >::value();
  }
  static const char* value(const ::dsr_msgs::SetRefCoordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dsr_msgs::SetRefCoordResponse> should match
// service_traits::MD5Sum< ::dsr_msgs::SetRefCoord >
template<>
struct MD5Sum< ::dsr_msgs::SetRefCoordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::SetRefCoord >::value();
  }
  static const char* value(const ::dsr_msgs::SetRefCoordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::SetRefCoordResponse> should match
// service_traits::DataType< ::dsr_msgs::SetRefCoord >
template<>
struct DataType< ::dsr_msgs::SetRefCoordResponse>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::SetRefCoord >::value();
  }
  static const char* value(const ::dsr_msgs::SetRefCoordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DSR_MSGS_MESSAGE_SETREFCOORD_H
