// Generated by gencpp from file dsr_msgs/SetSafetyMode.msg
// DO NOT EDIT!


#ifndef DSR_MSGS_MESSAGE_SETSAFETYMODE_H
#define DSR_MSGS_MESSAGE_SETSAFETYMODE_H

#include <ros/service_traits.h>


#include <dsr_msgs/SetSafetyModeRequest.h>
#include <dsr_msgs/SetSafetyModeResponse.h>


namespace dsr_msgs
{

struct SetSafetyMode
{

typedef SetSafetyModeRequest Request;
typedef SetSafetyModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSafetyMode
} // namespace dsr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dsr_msgs::SetSafetyMode > {
  static const char* value()
  {
    return "82c2323d83064354d4a93feb6b800608";
  }

  static const char* value(const ::dsr_msgs::SetSafetyMode&) { return value(); }
};

template<>
struct DataType< ::dsr_msgs::SetSafetyMode > {
  static const char* value()
  {
    return "dsr_msgs/SetSafetyMode";
  }

  static const char* value(const ::dsr_msgs::SetSafetyMode&) { return value(); }
};


// service_traits::MD5Sum< ::dsr_msgs::SetSafetyModeRequest> should match
// service_traits::MD5Sum< ::dsr_msgs::SetSafetyMode >
template<>
struct MD5Sum< ::dsr_msgs::SetSafetyModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::SetSafetyMode >::value();
  }
  static const char* value(const ::dsr_msgs::SetSafetyModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::SetSafetyModeRequest> should match
// service_traits::DataType< ::dsr_msgs::SetSafetyMode >
template<>
struct DataType< ::dsr_msgs::SetSafetyModeRequest>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::SetSafetyMode >::value();
  }
  static const char* value(const ::dsr_msgs::SetSafetyModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dsr_msgs::SetSafetyModeResponse> should match
// service_traits::MD5Sum< ::dsr_msgs::SetSafetyMode >
template<>
struct MD5Sum< ::dsr_msgs::SetSafetyModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dsr_msgs::SetSafetyMode >::value();
  }
  static const char* value(const ::dsr_msgs::SetSafetyModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dsr_msgs::SetSafetyModeResponse> should match
// service_traits::DataType< ::dsr_msgs::SetSafetyMode >
template<>
struct DataType< ::dsr_msgs::SetSafetyModeResponse>
{
  static const char* value()
  {
    return DataType< ::dsr_msgs::SetSafetyMode >::value();
  }
  static const char* value(const ::dsr_msgs::SetSafetyModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DSR_MSGS_MESSAGE_SETSAFETYMODE_H
